In [93]:
%config IPCompleter.greedy=True

In [94]:
import pandas as pd
import numpy as np

In [103]:
dataset = pd.read_csv("./data/FirstDataset.csv")

In [104]:
print(dataset)

  Location   Age  Salary Bonus Offered
0    Delhi  44.0   72000            No
1   Mumbai   NaN   48000            No
2   Mumbai  30.0   54000            No
3    Delhi  38.0   61000            No
4    Delhi  40.0   63000           Yes
5   Mumbai  38.0   58000           Yes
6  Chennai   NaN   52000            No
7   Mumbai  48.0   79000           Yes
8    Delhi  50.0   83000            No
9   Mumbai  37.0   67000         Maybe


In [97]:
#dataset = dataset.dropna()
#print(dataset)

In [98]:
#dataset = dataset.replace(np.nan, 30)
#print(dataset)

In [105]:
X = dataset.iloc[:, 0:3].values
print(X)

[['Delhi' 44.0 72000]
 ['Mumbai' nan 48000]
 ['Mumbai' 30.0 54000]
 ['Delhi' 38.0 61000]
 ['Delhi' 40.0 63000]
 ['Mumbai' 38.0 58000]
 ['Chennai' nan 52000]
 ['Mumbai' 48.0 79000]
 ['Delhi' 50.0 83000]
 ['Mumbai' 37.0 67000]]


In [106]:
y = dataset.iloc[:, 3].values
print(y)

['No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Maybe']


In [108]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")

imputer.fit(X[:, 1:2])
X[:, 1:2] = imputer.transform(X[:, 1:2])
print(X)

[['Delhi' 44.0 72000]
 ['Mumbai' 38.0 48000]
 ['Mumbai' 30.0 54000]
 ['Delhi' 38.0 61000]
 ['Delhi' 40.0 63000]
 ['Mumbai' 38.0 58000]
 ['Chennai' 38.0 52000]
 ['Mumbai' 48.0 79000]
 ['Delhi' 50.0 83000]
 ['Mumbai' 37.0 67000]]


In [110]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
y = labelEncoder.fit_transform(y)
print(y)

[1 1 1 1 2 2 1 2 1 0]


In [115]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
oneHotEncoder = OneHotEncoder()

ct = ColumnTransformer(transformers=[("encoder", oneHotEncoder, [0])], remainder="passthrough")
X = ct.fit_transform(X)
print(X)

[[0.0 1.0 0.0 44.0 72000]
 [0.0 0.0 1.0 38.0 48000]
 [0.0 0.0 1.0 30.0 54000]
 [0.0 1.0 0.0 38.0 61000]
 [0.0 1.0 0.0 40.0 63000]
 [0.0 0.0 1.0 38.0 58000]
 [1.0 0.0 0.0 38.0 52000]
 [0.0 0.0 1.0 48.0 79000]
 [0.0 1.0 0.0 50.0 83000]
 [0.0 0.0 1.0 37.0 67000]]
